apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "altimanager.fullname" . }}
  namespace: {{ template "altimanager.namespace" . }}
  labels:
    {{- include "altimanager.labels" . | nindent 4 }}
  annotations:
    checkov.io/skip1: "CKV_K8S_40=Container is using uid 1000 (predefined user node) by default"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "altimanager.selectorLabels" . | nindent 6 }}
{{- with .Values.deploymentStrategy }}
  strategy:
{{ toYaml . | trim | indent 4 }}
{{- end }}
  template:
    metadata:
      # https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmaps.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "altimanager.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      serviceAccountName: {{ include "altimanager.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      containers:
      - name: main
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        image: {{ include "altimanager.runner.image" . | quote }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        {{- with .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        command:
          - sh
          - -c
        args:
          - |
            echo "=======> Starting server only - do not run build as apps are already built here..."
            npm run server
        volumeMounts:
          - name: altimanager-external-volume
            mountPath: /altimanager-workspace/apihub-root/external-volume
          - name: altimanager-secret-volume
            mountPath: /altimanager-workspace/apihub-root/external-volume/config/apihub.json
            subPath: apihub.json
            readOnly: true
          - name: altimanager-bdns-config-volume
            mountPath: /altimanager-workspace/apihub-root/external-volume/config/bdns.hosts
            subPath: bdns.hosts
            readOnly: true
          - name: altimanager-secret-volume
            mountPath: /altimanager-workspace/env.json
            subPath: env.json
            readOnly: true
          - name: altimanager-domains-volume
            mountPath: /altimanager-workspace/apihub-root/external-volume/config/domains/{{ required "config.vaultDomain must be set" .Values.config.vaultDomain }}.json
            subPath: {{ required "config.vaultDomain must be set" .Values.config.vaultDomain }}.json
            readOnly: true
            #
            # Mounts for environment configs to trust-loader
            #

          - name: altimanager-env-volume
            mountPath: /altimanager-workspace/apihub-root/environment.js
            subPath: environment.js
            readOnly: true

      volumes:
        - name: altimanager-secret-volume
        {{- if .Values.secretProviderClass.enabled }}
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "altimanager.fullname" . }}
        {{- else }}
          secret:
            secretName: {{ include "altimanager.fullname" . }}
            defaultMode: 0400
        {{- end }}
        - name: altimanager-bdns-config-volume
          configMap:
            name: {{ include "altimanager.fullname" . }}-bdns
        - name: altimanager-domains-volume
          configMap:
            name: {{ include "altimanager.fullname" . }}-domains
        - name: altimanager-env-volume
          configMap:
            name: {{ include "altimanager.fullname" . }}-environment
        - name: altimanager-external-volume
          persistentVolumeClaim:
            claimName: {{ include "altimanager.pvc" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
