{{- if not .Values.secretProviderClass.enabled }}
{{- include "altimanager.secret" (list $ . "" (dict)) }}
{{- else }}
{{- include "altimanager.secretProviderClass" (list $ . "" (dict)) }}
{{- end }}
